--TRIGGER

/* CREATE TABLE TAB_FATURAMENTO (
    DATA_VENDA DATE NULL, 
    TOTAL_VENDA FLOAT
);

SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0100', '2018-05-15', '1471156710', '235', 0.18
);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES (
    '0100', '1000889', 100, 10
);

INSERT INTO TABELA_DE_VENDAS 
VALUES ('0101', '2018-05-15', '1471156710', '235', 0.18);
INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES ('0101', '1000889', 100, 10);

--INSERINDO DADOS NA TABELA FATURAMENTO
INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;
*/

SELECT * FROM TAB_FATURAMENTO;

--QUANDO INSERIRMOS NA TABELA DE VENDAS E DE ITENSVENDIDOS, QUEREMOS INSERIR NA TAB_FATURAMENTO

INSERT INTO TABELA_DE_VENDAS 
VALUES ('0105', '2018-05-16', '1471156710', '235', 0.18);
INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES ('0105', '1000889', 1500, 10);

--ATUALIZA TAB_FATURAMENTO
DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

-- CRIANDO A TRIGGER
CREATE TRIGGER TG_ITENS_VENDIDOS
ON [dbo].[TABELA_DE_ITENS_VENDIDOS]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA

END;

UPDATE TABELA_DE_ITENS_VENDIDOS SET QUANTIDADE = 200 WHERE NUMERO = '0105';

SELECT * FROM TAB_FATURAMENTO;

