--AUTO INCREMENT

CREATE TABLE TAB_IDENTITY (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);

SELECT * FROM TAB_IDENTITY

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES 
('CLIENTE A'),
('CLIENTE B'),
('CLIENTE C'),
('CLIENTE D'),
('CLIENTE E');


CREATE TABLE TAB_IDENTITY2 (
    ID INT IDENTITY(100,5) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);

--AUTO INCREMENT DE 5 EM 5 COMEÇANDO DE 100
INSERT INTO TAB_IDENTITY2 (DESCRITOR) 
VALUES 
('CLIENTE A'),
('CLIENTE B'),
('CLIENTE C'),
('CLIENTE D'),
('CLIENTE E');

SELECT * FROM TAB_IDENTITY2


--PADROES PARA CAMPOS

CREATE TABLE TB_PADRAO (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR(20) NULL, 
    ENDERECO VARCHAR(20) NULL, 
    CIDADE VARCHAR(20) DEFAULT 'Rio de Janeiro', 
    DATA_CRIACAO DATE DEFAULT GETDATE()
);

INSERT INTO TB_PADRAO 
    (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO) 
VALUES
    ('CLIENTE X', 'RUA PROJETADA A', 'SÃO PAULO', '2018-04-30');

SELECT * FROM TB_PADRAO;

INSERT INTO TB_PADRAO (DESCRITOR) 
VALUES ('CLIENTE Y');
