--ALTERANDO DADOS NA TABELA

SELECT * FROM PRODUTOS;

UPDATE PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1040107';


-- AUMENTANDO 10% NO PREÇO

SELECT * FROM PRODUTOS WHERE SABOR = 'MANGA';

UPDATE PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 1.1
WHERE SABOR = 'MANGA';

--ALTERANDO TAMANHOS

SELECT DESCRITOR FROM PRODUTOS WHERE TAMANHO = '550 ml';

--SELECT ALTERANDO O ML
SELECT DESCRITOR, replace (DESCRITOR, '350 ml', '550 ml') FROM PRODUTOS WHERE TAMANHO = '350 ml';

--UPDATE
UPDATE PRODUTOS SET 
    DESCRITOR = replace(DESCRITOR, '350 ml', '550 ml'), 
    TAMANHO = '550 ml' 
WHERE TAMANHO = '350 ml';



--DESAFIO: Modifique o endereço do cliente 19290992743 para R. Jorge Emilio 23, em Santo Amaro, São Paulo, SP, CEP 8833223.

SELECT * FROM CLIENTES WHERE CPF = 19290992743;

UPDATE CLIENTES 
SET ENDERECO = 'R. Jorge Emilio 23', 
BAIRRO = 'Santo Amaro', 
CIDADE = 'São Paulo', 
ESTADO = 'SP', 
CEP = '8833223'
WHERE CPF = 19290992743;


--DESAFIO: alterando o volume de compra em 20% dos clientes do estado do Rio de Janeiro

SELECT VOLUME_COMPRA FROM CLIENTES WHERE ESTADO = 'RJ';

UPDATE CLIENTES 
SET VOLUME_COMPRA = VOLUME_COMPRA * 1.2
WHERE ESTADO = 'RJ';



--UPDATE COM FROM

SELECT * FROM PRODUTOS ORDER BY CODIGO;
SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS 
ORDER BY CODIGO_DO_PRODUTO;

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET 
PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;


--UPDATE COM INNER JOIN

SELECT 
A.CODIGO AS CODIGO_MINHA_TABELA, A.PRECO_LISTA AS PRECO_MINHA_TABELA, 
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO, B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO 
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;


--DESAFIO: aumentar em 30% o volume de compra dos clientes que possuem, em seus endereços, bairros onde os vendedores possuam escritórios

SELECT C.NOME, C.BAIRRO, V.BAIRRO, C.VOLUME_COMPRA 
FROM CLIENTES C
INNER JOIN VENDEDORES V
ON C.BAIRRO = V.BAIRRO;

UPDATE C
SET C.VOLUME_COMPRA = C.VOLUME_COMPRA * 1.3
FROM CLIENTES C
INNER JOIN VENDEDORES V
ON C.BAIRRO = V.BAIRRO;



--MERGE: MAIS USADO PARA TRANSFERIR DADOS ENTRE TABELAS

SELECT 
A.CODIGO AS CODIGO_MINHA_TABELA, A.PRECO_LISTA AS PRECO_MINHA_TABELA, 
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO, B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO 
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;


MERGE INTO PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;


--DEAFIO: aumentar em 30% o volume de compra dos clientes que possuem, em seus endereços, bairros onde os vendedores possuam escritórios
MERGE INTO CLIENTES C
USING VENDEDORES V 
ON C.BAIRRO = V.BAIRRO
WHEN MATCHED THEN
UPDATE SET C.VOLUME_COMPRA = C.VOLUME_COMPRA * 1.3;



-- DELETANDO DADOS

--dados para deletar
INSERT INTO PRODUTOS 
    (CODIGO,DESCRITOR,SABOR,TAMANHO,EMBALAGEM,PRECO_LISTA)
VALUES 
    ('1001001','Sabor dos Alpes 700 ml - Manga','Manga','700 ml','Garrafa',7.50),
    ('1001000','Sabor dos Alpes 700 ml - Melão','Melão','700 ml','Garrafa',7.50),
    ('1001002','Sabor dos Alpes 700 ml - Graviola','Graviola','700 ml','Garrafa',7.50),
    ('1001003','Sabor dos Alpes 700 ml - Tangerina','Tangerina','700 ml','Garrafa',7.50),
    ('1001004','Sabor dos Alpes 700 ml - Abacate','Abacate','700 ml','Garrafa',7.50),
    ('1001005','Sabor dos Alpes 700 ml - Açai','Açai','700 ml','Garrafa',7.50),
    ('1001006','Sabor dos Alpes 1 Litro - Manga','Manga','1 Litro','Garrafa',7.50),
    ('1001007','Sabor dos Alpes 1 Litro - Melão','Melão','1 Litro','Garrafa',7.50),
    ('1001008','Sabor dos Alpes 1 Litro - Graviola','Graviola','1 Litro','Garrafa',7.50),
    ('1001009','Sabor dos Alpes 1 Litro - Tangerina','Tangerina','1 Litro','Garrafa',7.50),
    ('1001010','Sabor dos Alpes 1 Litro - Abacate','Abacate','1 Litro','Garrafa',7.50),
    ('1001011','Sabor dos Alpes 1 Litro - Açai','Açai','1 Litro','Garrafa',7.50);

SELECT * FROM [PRODUTOS] WHERE SUBSTRING([DESCRITOR], 1, 15) = 'Sabor dos Alpes';

--DELETE
DELETE FROM PRODUTOS WHERE CODIGO = '1001000';

DELETE FROM PRODUTOS WHERE 
    SUBSTRING([DESCRITOR], 1, 15) = 'Sabor dos Alpes' 
    AND TAMANHO = '1 Litro';


--DELETANDO PRODUTOS QUE NAO TEM EM OUTRA TABELA

SELECT * FROM PRODUTOS 
WHERE CODIGO NOT IN (
    SELECT CODIGO_DO_PRODUTO 
    FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS);

	DELETE FROM PRODUTOS 
WHERE CODIGO NOT IN (
    SELECT CODIGO_DO_PRODUTO 
    FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS);


--DEAFIO: Exclua as notas fiscais (apenas o cabeçalho) cujos clientes tenham menos que 18 anos.
DELETE A FROM TABELA_DE_VENDAS A
INNER JOIN [CLIENTES] B 
ON A.[CPF] = B.[CPF] 
WHERE B.[IDADE] < 18;

SELECT A.NUMERO FROM TABELA_DE_VENDAS A
INNER JOIN [CLIENTES] B ON A.[CPF] = B.[CPF] 



--COMMIT E ROLLBACK

SELECT * FROM VENDEDORES
 
--
BEGIN TRANSACTION

UPDATE VENDEDORES SET COMISSAO = COMISSAO * 1.1

COMMIT

BEGIN TRANSACTION

UPDATE VENDEDORES SET COMISSAO = COMISSAO / 1.1

ROLLBACK