CREATE DATABASE VENDAS_SUCOS;

/*

CREATE DATABASE [VENDAS SUCOS 2]
ON(
NAME='VENDAS_SUCOS_2_DAT',
FILENAME='C:\TEM\VENDAS_SUCOS_2_.MDF',
SIZE=10MB,
MAXSIZE=50,
FILEGROUND=5
)
LOG_ON (
NAME='VENDAS_SUCOS_2_LOG',
FILENAME='C:\TEM\VENDAS_SUCOS_2_.LDF',
SIZE=10MB,
MAXSIZE=50,
FILEGROUND=5
);

DROP DATABASE [VENDAS SUCOS 2];

*/

CREATE TABLE PRODUTOS (
    CODIGO VARCHAR(10) NOT NULL, 
    DESCRITOR VARCHAR(100) NULL, 
    SABOR VARCHAR(50) NULL, 
    TAMANHO VARCHAR(50) NULL, 
    EMBALAGEM VARCHAR(50) NULL, 
    PRECO_LISTA FLOAT NULL, 
    PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES (
    MATRICULA VARCHAR(5) NOT NULL, 
    NOME VARCHAR(100) NULL, 
    BAIRRO VARCHAR(50) NULL, 
    COMISSAO FLOAT NULL, 
    DATA_ADMISSAO DATE NULL, 
    FERIAS BIT NULL, 
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE CLIENTE ( 
CPF VARCHAR (11) NOT NULL, 
NOME VARCHAR (100) NULL, 
ENDERECO VARCHAR (150) NULL, 
BAIRRO VARCHAR (50) NULL, 
CIDADE VARCHAR (50) NULL, 
ESTADO VARCHAR (50) NULL, 
CEP VARCHAR (8) NULL, 
DATA_NASCIMENTO DATE NULL, 
IDADE SMALLINT NULL, 
GENERO VARCHAR (1) NULL, 
LIMITE_CREDITO FLOAT NULL, 
COLUME_COMPRA FLOAT NULL, 
PRIMEIRA_COMPRA BIT NULL,
PRIMARY KEY (CPF)
) ;

CREATE TABLE TABELA_DE_VENDAS (
    NUMERO VARCHAR(5) NOT NULL, 
    DATA_VENDA DATE NULL, 
    CPF VARCHAR(11) NOT NULL, 
    MATRICULA VARCHAR(11) NOT NULL, 
    IMPOSTO FLOAT NULL, 
    PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_CLIENTES 
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_VENDEDORES 
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);
--ERRO PORQUE O TAMANHO DO VARCHAR() É DIFERENTE

ALTER TABLE TABELA_DE_VENDAS 
ALTER COLUMN MATRICULA VARCHAR(5) NOT NULL
--CORRIGIDO. Agora pode ser executato o codigo acima

CREATE TABLE TABELA_DE_ITENS_VENDIDOS
(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE FLOAT NULL,
PRECO FLOAT NULL,
PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE TABELA_DE_ITENS_VENDIDOS
ADD CONSTRAINT FK_NUMERO
FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);

ALTER TABLE TABELA_DE_ITENS_VENDIDOS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);