-- NOME + CPF

SELECT * FROM TABELA_DE_CLIENTES;

DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
SELECT @NUMERO_CLIENTES = COUNT(*) FROM TABELA_DE_CLIENTES;
SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES
BEGIN
        SELECT @CPF = X.CPF, @NOME = X.NOME
        FROM ( SELECT Row_Number() Over (Order By CPF) as RowNum, * FROM TABELA_DE_CLIENTES) X
        WHERE X.RowNum = @I;
        PRINT @CPF + ' - ' + @NOME;
        SET @I = @I + 1;
END;


-- CALCULANDO AS VENDAS

DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;
DECLARE @TABELA_FINAL TABLE (CPF VARCHAR(11), NOME VARCHAR(100), MES INT, ANO INT, VALOR_TOTAL FLOAT); 

SET @MES = 1;
SET @ANO = 2015;
SELECT @NUMERO_CLIENTES = COUNT(*) FROM TABELA_DE_CLIENTES;
SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES
BEGIN
        SELECT @CPF = X.CPF, @NOME = X.NOME
        FROM ( SELECT Row_Number() Over (Order By CPF) as RowNum, * FROM TABELA_DE_CLIENTES) X
        WHERE X.RowNum = @I;

                SELECT 
                @TOTAL_VENDAS = SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE * ITENS_NOTAS_FISCAIS.PRECO)
                FROM NOTAS_FISCAIS 
                INNER JOIN ITENS_NOTAS_FISCAIS
                ON NOTAS_FISCAIS.NUMERO = ITENS_NOTAS_FISCAIS.NUMERO
                WHERE NOTAS_FISCAIS.CPF = @CPF
                AND YEAR(NOTAS_FISCAIS.DATA_VENDA) = @ANO AND MONTH(NOTAS_FISCAIS.DATA_VENDA) = @MES;

				INSERT INTO @TABELA_FINAL VALUES (@CPF, @NOME, @MES, @ANO, @TOTAL_VENDAS);

        PRINT 'Vendas para ' + @CPF + ' - ' + @NOME + ' NO MÊS ' + CONVERT(VARCHAR(2), @MES) + ' E ANO ' + CONVERT(VARCHAR(4),@ANO) + ' FOI DE ' + TRIM(STR(@TOTAL_VENDAS, 15, 2));
        SET @I = @I + 1;
END;

SELECT * FROM @TABELA_FINAL
