-- CONTROLE DE FLUXO WHILE

DECLARE @LIMITE_MINIMO INT;
DECLARE @LIMITE_MAXIMO INT;

SET @LIMITE_MINIMO = 3;
SET @LIMITE_MAXIMO = 30;

PRINT 'ENTREI NO LOOPING';
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
    PRINT @LIMITE_MINIMO;
    SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1;
END;
PRINT 'SAI DO LOOPING';


--BREAK

DECLARE @LIMITE_MINIMO INT;
DECLARE @LIMITE_MAXIMO INT;
DECLARE @NUM_LINHAS_MAX INT;
DECLARE @NUM_LINHAS_ESCRITAS INT;

SET @LIMITE_MINIMO = 3;
SET @LIMITE_MAXIMO = 30;
SET @NUM_LINHAS_MAX = 10;
SET @NUM_LINHAS_ESCRITAS = 0;

PRINT 'ENTREI NO LOOPING';
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
    PRINT @LIMITE_MINIMO;
        SET @NUM_LINHAS_ESCRITAS = @NUM_LINHAS_ESCRITAS +1;
        IF @NUM_LINHAS_ESCRITAS = @NUM_LINHAS_MAX
        BEGIN
            PRINT 'SAI DO LOOPING POR CAUSA DO BREAK';
            BREAK;
        END;
    SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1;
END;
PRINT 'SAI DO LOOPING';



-- INSERINDO NA TABELA COM WHILE


IF OBJECT_ID('TABELA DE NUMEROS', 'U') IS NOT NULL DROP TABLE [TABELA DE NUMEROS];
CREATE TABLE [TABELA DE NUMEROS] ([NUMERO] INT, [STATUS] VARCHAR(20));

DECLARE @NUMERO_INICIAL_SEQUENCIA INT, @NUMERO_FINAL_SEQUENCIA INT;
DECLARE @TESTE_NOTA_FISCAL INT;
SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 100000;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA
BEGIN
	SELECT @TESTE_NOTA_FISCAL = COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = @NUMERO_INICIAL_SEQUENCIA
	IF @TESTE_NOTA_FISCAL = 1
		INSERT INTO [TABELA DE NUMEROS] (NUMERO, STATUS) 
		VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');
	ELSE
		INSERT INTO [TABELA DE NUMEROS] (NUMERO, STATUS) 
		VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃO É NOTA FISCAL');
	SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;
END

SELECT * FROM [TABELA DE NUMEROS]


--FOR 

--FOR I =1 TO 100
--<COMANDOS>
--NEXT

DECLARE @I INT;

SET @I =1;

WHILE @I <= 100
BEGIN
    PRINT @I;
    SET @I = @I +1;
END;