
SELECT SUM(QUANTIDADE * PREÇO) 
FROM [ITENS NOTAS FISCAIS]
WHERE NUMERO = 100;


-- CRIANDO FUNÇÃO FaturamentoNota
CREATE FUNCTION FaturamentoNota(@NUMERO AS INT)
RETURNS FLOAT
AS
BEGIN
   DECLARE @FATURAMENTO FLOAT
   SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO])
   FROM [dbo].[ITENS NOTAS FISCAIS]
   WHERE NUMERO = @NUMERO
   RETURN @FATURAMENTO 
END;

--CHAMANDO FUNÇÃO FaturamentoNota
SELECT NUMERO, dbo.FaturamentoNota(NUMERO) AS FATURAMENTO
FROM [dbo].[NOTAS FISCAIS] 



-- FUNÇÃO 
CREATE FUNCTION NumeroAleatorio(@VAL_MIN INT, @VAL_MAX INT)
RETURNS INT
AS
BEGIN
  DECLARE @ALEATORIO INT
  DECLARE @VALOR_ALEATORIO FLOAT
  SELECT @VALOR_ALEATORIO = VALOR_ALEATORIO FROM VW_ALEATORIO
  SET @ALEATORIO = ROUND(((@VAL_MAX - @VAL_MIN - 1) * @VALOR_ALEATORIO + @VAL_MIN, 0)
  RETURN @ALEATORIO
END