SELECT CPF, NOME, [DATA DE NASCIMENTO]
FROM [TABELA DE CLIENTES];

--CALCULANDO IDADE
SELECT CPF, NOME, [DATA DE NASCIMENTO], IDADE, DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE()) FROM [TABELA DE CLIENTES]


--PROCECDURE CalculaIdade
CREATE PROCEDURE CalculaIdade
AS
BEGIN
 UPDATE [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END

--executando a procedure
EXEC [dbo].[CalculaIdade]



--PROCEDURE COM ENTRADA ESCALAR

CREATE PROCEDURE BuscaNotasCliente
@CPF AS VARCHAR(12) = '19290992743',
@DATA_INICIAL AS DATETIME = '20160101',
@DATA_FINAL AS DATETIME = '20161231'
AS
BEGIN
   SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF
   AND DATA >= @DATA_INICIAL AND DATA <= @DATA_FINAL
END;

--ALTERANDO OS VALORES AO CHAMAR A PROCEDURE
EXEC BuscaNotasCliente '19290992743', '20160501'

EXEC BuscaNotasCliente @CPF='19290992743', @DATA_INICIAL='20160501', @DATA_FINAL='20160615'

EXEC BuscaNotasCliente @CPF='19290992743', @DATA_FINAL='20160615'



--PROCEDURE COM ENTRADA POR REFERÊNCIA

CREATE PROCEDURE retornaValoresFaturamentoQuantidade
@CPF AS VARCHAR(12), @ANO AS INT, 
@NUM_NOTAS AS INT OUTPUT, @FATURAMENTO AS FLOAT OUTPUT --OUTPUT (a varável será alterada também fora da procedure)
AS
BEGIN

SELECT @NUM_NOTAS = COUNT(*) FROM [NOTAS FISCAIS]
WHERE CPF = @CPF AND YEAR([DATA]) = @ANO

SELECT @FATURAMENTO = SUM(INF.QUANTIDADE * INF.[PREÇO])
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [NOTAS FISCAIS] NF
ON INF.NUMERO = NF.NUMERO
WHERE NF.CPF = @CPF AND YEAR(NF.[DATA]) = @ANO

END


DECLARE @NUM_NOTAS INT
DECLARE @FATURAMENTO FLOAT

SET @NUM_NOTAS = 0
SET @FATURAMENTO = 0

SELECT @NUM_NOTAS, @FATURAMENTO

EXEC retornaValoresFaturamentoQuantidade @CPF='19290992743', @ANO=2017,
@NUM_NOTAS=@NUM_NOTAS OUTPUT, @FATURAMENTO=@FATURAMENTO OUTPUT

SELECT @NUM_NOTAS, @FATURAMENTO