SELECT DISTINCT [data] FROM tb_nota order by [data] DESC

-- 2022-03-02

CREATE TABLE tb_controle_backups 
(ID INTEGER, NOME VARCHAR(100), NUM_NOTAS INTEGER);


-- 1 DA MANHA - FULL (DATABASE WITH INT)
-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 6 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 8 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 9 DA MANHÃ - FULL (DATABASE WITH DIFFERENTIAL)
-- 10 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 12 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 2 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 2 DA TARDE - FULL (DATABASE WITH DIFFERENTIAL)
-- 3 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 5 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 7 DA NOITE - INCREMENTAL (LOG WITH NOINT)
-- 9 DA NOITE - INCREMENTAL (LOG WITH NOINT)

-- 1 DA MANHA - FULL (DATABASE WITH INT)

EXEC IncluiNotasDia '2022-03-02'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (1, 'BACKUP FULL 1 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP DATABASE dbVendas TO DISK = 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH INIT;


-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (2, 'BACKUP INCREMENTAL 4 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;


-- 6 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (3, 'BACKUP INCREMENTAL 6 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;


-- 8 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia '2022-03-02'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (4, 'BACKUP INCREMENTAL 8 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK' WITH NOINIT;
