RESTORE HEADERONLY FROM
DISK = 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK'

USE MASTER;
ALTER DATABASE dbVendas SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE dbVendas;

RESTORE DATABASE dbVendas FROM DISK 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 1, NORECOVERY;

RESTORE DATABASE dbVendas FROM DISK 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 9, NORECOVERY;

RESTORE DATABASE dbVendas FROM DISK 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 10, NORECOVERY;

RESTORE DATABASE dbVendas FROM DISK 'C:\SQLServer22\BACKUP\POLITICA_BACKUP_20220302.BAK'
WITH FILE = 11, RECOVERY;
