-- Para calcular a quantidade vendida por cliente
SELECT
  NF.CPF,
  NF.DATA_VENDA,
  INF.QUANTIDADE
FROM
  NOTAS_FISCAIS NF
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO;

-- Para agregar dentro de um mesmo mês
SELECT
  NF.CPF,
  TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
  INF.QUANTIDADE
FROM
  NOTAS_FISCAIS NF
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO;

-- Agrupe
SELECT
  NF.CPF,
  TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
  SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
  NOTAS_FISCAIS NF
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY
  CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY');

-- Olhe a tabela de clientes
SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;

-- Junte o resultado da query da tabela de clientes com o resultado da consulta anterior, mostrando o cadastro e a quantidade total
SELECT
  TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL
FROM
  TABELA_DE_CLIENTES TC
  INNER JOIN (
    SELECT
      NF.CPF,
      TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
      SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM
      NOTAS_FISCAIS NF
      INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
    GROUP BY
      CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
  ) TV ON TV.CPF = TC.CPF;

-- Coloque o CASE para testar se as vendas são válidas
SELECT
  TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
  (CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS' ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO
FROM
  TABELA_DE_CLIENTES TC
  INNER JOIN (
    SELECT
      NF.CPF,
      TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
      SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM
      NOTAS_FISCAIS NF
      INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
    GROUP BY
      CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
  ) TV ON TV.CPF = TC.CPF;

-- Agora, escolha a data que quer verificar
SELECT
  TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
  (CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS' ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO
FROM
  TABELA_DE_CLIENTES TC
  INNER JOIN (
    SELECT
      NF.CPF,
      TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
      SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    FROM
      NOTAS_FISCAIS NF
      INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
    GROUP BY
      CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
  ) TV ON TV.CPF = TC.CPF
WHERE
  TV.MES_ANO = '02-2015';

-- O novo desafio é o ranking das vendas dos produtos por sabor e uma coluna do percentual de vendas no ano

-- Crie um novo script e desenvolva o código para pegar as vendas totais por sabor
SELECT
  TP.SABOR,
  INF.QUANTIDADE,
  NF.DATA_VENDA
FROM
  TABELA_DE_PRODUTOS TP
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
  INNER JOIN NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO;

-- Melhore o código, para mostrar dentro do ano
SELECT
  TP.SABOR,
  INF.QUANTIDADE,
  EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
FROM
  TABELA_DE_PRODUTOS TP
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
  INNER JOIN NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO;

-- De maneira a mostrar o ranking de vendas no ano 2016, ordenando pela soma das quantidades, execute
SELECT
  TP.SABOR,
  EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
  SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
  TABELA_DE_PRODUTOS TP
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
  INNER JOIN NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO
WHERE
  EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY
  TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY
  SUM(INF.QUANTIDADE) DESC;

-- Para mostrar a consulta da data e quantidade de vendas
SELECT
  NF.DATA_VENDA,
  INF.QUANTIDADE
FROM
  NOTAS_FISCAIS NF
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO;

-- Altere o código para mostrar o total de vendas em litros
SELECT
  TOTAL_ANO.QUANTIDADE_GERAL
FROM
  (
    SELECT
      EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
      SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
    FROM
      NOTAS_FISCAIS NF
      INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
    WHERE
      EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
    GROUP BY
      EXTRACT(YEAR FROM NF.DATA_VENDA)
  ) TOTAL_ANO;



-- Juntando as consultas, você terá
SELECT
  TP.SABOR,
  EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
  SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
  (
    SELECT
      TOTAL_ANO.QUANTIDADE_GERAL
    FROM
      (
        SELECT
          EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
          SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
        FROM
          NOTAS_FISCAIS NF
          INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
        WHERE
          EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
        GROUP BY
          EXTRACT(YEAR FROM NF.DATA_VENDA)
      ) TOTAL_ANO
  ) AS QUANTIDADE_GERAL
FROM
  TABELA_DE_PRODUTOS TP
  INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
  INNER JOIN NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO
WHERE
  EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY
  TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY
  SUM(INF.QUANTIDADE) DESC;

-- Para finalizar, o código completo que calcula e mostra a quantidade de vendas por sabor em determinado ano
SELECT
  CONSULTA_RELATORIO.SABOR,
  CONSULTA_RELATORIO.ANO,
  CONSULTA_RELATORIO.QUANTIDADE_TOTAL,
  ROUND((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.QUANTIDADE_GERAL) * 100, 2) AS PERCENTUAL_PARTICIPACAO
FROM
  (
    SELECT
      TP.SABOR,
      EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
      SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
      (
        SELECT
          TOTAL_ANO.QUANTIDADE_GERAL
        FROM
          (
            SELECT
              EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
              SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
            FROM
              NOTAS_FISCAIS NF
              INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
            WHERE
              EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
            GROUP BY
              EXTRACT(YEAR FROM NF.DATA_VENDA)
          ) TOTAL_ANO
      ) AS QUANTIDADE_GERAL
    FROM
      TABELA_DE_PRODUTOS TP
      INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
      INNER JOIN NOTAS_FISCAIS NF ON INF.NUMERO = NF.NUMERO
    WHERE
      EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
    GROUP BY
      TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
    ORDER BY
      SUM(INF.QUANTIDADE) DESC
  ) CONSULTA_RELATORIO;