SELECT * FROM TABELA_DE_CLIENTES;

-- LOWER & UPPER
SELECT NOME, 
LOWER(NOME) AS NOME_MINUSCULO, 
UPPER(NOME) AS NOME_MAIUSCULO  
FROM TABELA_DE_CLIENTES;

--CONCAT
SELECT NOME, CONCAT(ENDERECO_1, ', ', BAIRRO, ' | ', CIDADE, ' - ', ESTADO, ' | ', CEP) AS ENDERECO_COMPLETO 
FROM TABELA_DE_CLIENTES;

--CONTENANDO COM '+'
SELECT NOME, ENDERECO_1 + ' ' + BAIRRO + ' ' + CIDADE + ' ' + ESTADO + ' ' + CEP AS ENDERECO_COMPLETO 
FROM TABELA_DE_CLIENTES;

--LEFT
SELECT NOME_DO_PRODUTO, LEFT(NOME_DO_PRODUTO, 3) AS TRES_PRIMEIROS_CHAR 
FROM TABELA_DE_PRODUTOS;

--REPLACE
SELECT TAMANHO, REPLACE((REPLACE(TAMANHO, 'Litros', 'L')), 'Litro', 'L') AS TAMANHO_MODIFICADO 
FROM TABELA_DE_PRODUTOS;

--DESAFIO: somente o primeiro nome de cada cliente
SELECT NOME FROM TABELA_DE_CLIENTES;

SELECT NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME)) AS PRIMEIRO_NOME 
FROM TABELA_DE_CLIENTES;

--DATES

SELECT GETDATE() --dia de hoje

SELECT DATEADD(DAY, 30, GETDATE()) AS DATA_DAQUI_A_30_DIAS; --deteadd

SELECT DATEADD(DAY, -30, GETDATE()) AS DATA_30_DIAS_ATRAS; --deteadd(subtraindo)

SELECT DATEDIFF(DAY, '2023-01-01', GETDATE()) AS DIAS_DESDE_INICIO_ANO; --datediff(day)

SELECT DATEDIFF(HOUR, '2023-01-01', GETDATE()) AS HORAS_DESDE_INICIO_ANO; --datediff(hour)

SELECT DATEDIFF(MONTH, '2023-01-01', GETDATE()) AS MESES_DESDE_INICIO_ANO; --datediff(month)

SELECT DATEPART(DAY, GETDATE()) AS DIA_DE_HOJE; --datepart

SELECT ISDATE('2003-05-10')

SELECT ISDATE(DATETIMEFROMPARTS(2022, 02, 28, 00, 00, 00, 00)); --isdate

--IDADE DOS CLIENTES
SELECT NOME, DATEDIFF(YEAR, DATA_DE_NASCIMENTO, GETDATE()) AS IDADE FROM TABELA_DE_CLIENTES;

--DESAFIO: 
SELECT CONCAT
(NOME, ', '
,DATENAME(DAY, DATA_DE_NASCIMENTO), ' de '
,DATENAME(MONTH, DATA_DE_NASCIMENTO), ' de '
,DATENAME(YEAR, DATA_DE_NASCIMENTO)) AS NOME_E_DATA_DE_NASCIMENTO
FROM TABELA_DE_CLIENTES


--FUNÇÕES NUMÉRICAS

SELECT ROUND (3.433, 2) AS ROUND_2,
ROUND (3.433, 0) AS ROUND_0,
CEILING(3.433) AS CEILING,
FLOOR(3.433) AS FLOOR,
POWER(3.433, 2) AS POWER_2,
EXP(3) AS EXP,
SQRT(3.433) AS SQRT,
ABS(-3.433) AS ABS
;

--DESAFIO: Calcule o valor do imposto pago no ano de 2016, arredondando para o menor inteiro
SELECT YEAR(NF.DATA_VENDA) AS ANO, 
FLOOR(SUM(NF.IMPOSTO*INF.QUANTIDADE*INF.PRECO)) AS IMPOSTO_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY YEAR(NF.DATA_VENDA)


--FUNÇÕES DE CONVERSÃO

SELECT CONVERT(VARCHAR(25), GETDATE(), 121); --DATA PARA VARCHAR

SELECT DATA_DE_NASCIMENTO,
CONVERT(VARCHAR(10), DATA_DE_NASCIMENTO, 103) AS DATA_BR
FROM TABELA_DE_CLIENTES;

--CONVERSÃO IMPLÍCITA
SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', PRECO_DE_LISTA) AS PRECO 
FROM TABELA_DE_PRODUTOS;

--CONVERSÃO EXPLÍCITA COM CAST
SELECT NOME_DO_PRODUTO, 
CONCAT('O preço de lista é: ', CAST(PRECO_DE_LISTA AS VARCHAR(10))) AS PRECO 
FROM TABELA_DE_PRODUTOS;

--DESAFIO: "O cliente João da Silva comprou R$ 121222,12 no ano de 2016".
SELECT 
CONCAT('O cliente ',C.NOME,' comprou ',STR(SUM(INF.QUANTIDADE*INF.PRECO),11,3), ' no ano de 2016')
FROM TABELA_DE_CLIENTES C
INNER JOIN NOTAS_FISCAIS NF
ON C.CPF=NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO=INF.NUMERO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY C.NOME;