--VENDAS ANUAIS POR SABOR ORDENADO MAIS VENDEU > MENOS VENDEU

SELECT 
P.SABOR,
YEAR(N.DATA_VENDA) AS ANO_VENDA,
SUM(I.QUANTIDADE) AS QUANTIDADE
FROM TABELA_DE_PRODUTOS P
INNER JOIN ITENS_NOTAS_FISCAIS I
ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS N
ON N.NUMERO = I.NUMERO
WHERE YEAR(N.DATA_VENDA) = '2015'
GROUP BY P.SABOR, YEAR(N.DATA_VENDA)
ORDER BY QUANTIDADE DESC;


SELECT 
YEAR(N.DATA_VENDA) AS ANO,
SUM(I.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM NOTAS_FISCAIS N
INNER JOIN ITENS_NOTAS_FISCAIS I
ON N.NUMERO = I.NUMERO
WHERE YEAR(N.DATA_VENDA) = '2015'
GROUP BY YEAR(N.DATA_VENDA);


-------------------------------------------------------------------------------------------------
SELECT
    S.SABOR,
    S.ANO_VENDA,
    S.QUANTIDADE,
    ROUND((CONVERT(FLOAT, S.QUANTIDADE) / T.VENDA_TOTAL_ANO) * 100, 2) AS 'PERCENTUAL (%)'
FROM
    (SELECT 
        P.SABOR,
        YEAR(N.DATA_VENDA) AS ANO_VENDA,
        SUM(I.QUANTIDADE) AS QUANTIDADE
    FROM
        TABELA_DE_PRODUTOS P
    INNER JOIN
        ITENS_NOTAS_FISCAIS I ON P.CODIGO_DO_PRODUTO = I.CODIGO_DO_PRODUTO
    INNER JOIN
        NOTAS_FISCAIS N ON N.NUMERO = I.NUMERO
    GROUP BY
        P.SABOR, YEAR(N.DATA_VENDA)) S

INNER JOIN
    (SELECT 
        YEAR(N.DATA_VENDA) AS ANO,
        SUM(I.QUANTIDADE) AS VENDA_TOTAL_ANO
    FROM
        NOTAS_FISCAIS N
    INNER JOIN
        ITENS_NOTAS_FISCAIS I ON N.NUMERO = I.NUMERO
    GROUP BY
        YEAR(N.DATA_VENDA)) T

ON
    S.ANO_VENDA = T.ANO
WHERE
    S.ANO_VENDA = '2015'
ORDER BY
    S.QUANTIDADE DESC;
