--SE A TABELA EXISTIR (NOT NULL): DROP
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL
	DROP TABLE TABELA_TESTE;

--SE A TABELA NÃO EXISTIR (IS NULL): CREATE
IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL
	CREATE TABLE TABELA_TESTE (ID INT IDENTITY(1,1) PRIMARY KEY);

DROP TABLE TABELA_TESTE;


PRINT GETDATE()


--DIA DA SEMANA + NUM DE DIAS = MEIO OU FIM DE SEMANA

DECLARE @NUMDIAS INT
DECLARE @DIA VARCHAR(15)

SET @NUMDIAS = 7;
SET @DIA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMDIAS, GETDATE()))

IF @DIA IN ('Saturday', 'Sunday')
	PRINT 'Fds, pode relaxar!'
ELSE IF @DIA = 'Friday'
	PRINT 'Sextou!!'
ELSE 
	PRINT 'Terá que trabalhar'


-- Controle de fluxo usando SELECT

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) AS 'SOMA LIMITE DE CRÉDITO' FROM [TABELA DE CLIENTES] GROUP BY BAIRRO;

SELECT SUM([LIMITE DE CREDITO]) AS 'SOMA LIMITE DE CRÉDITO' FROM [TABELA DE CLIENTES] WHERE BAIRRO = 'Água Santa';
--------------------------------------------------------------------------

DECLARE @LIMITE_MAXIMO FLOAT;
DECLARE @LIMITE_ATUAL FLOAT;
DECLARE @BAIRRO VARCHAR(20);

SET @LIMITE_MAXIMO = 50000;
SET @BAIRRO = 'Água Santa';
SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE @BAIRRO = 'Água Santa';

IF @LIMITE_MAXIMO <= @LIMITE_ATUAL
	PRINT 'VALOR ESTOUROU !!'
ELSE
	PRINT 'VALOR OK';