SELECT nome, [primeira compra]
FROM tabela_clientes
WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA_PRODUTOS] 
WHERE [PRECO DE LISTA] > 7.00

SELECT * FROM [TABELA_PRODUTOS] 
WHERE [EMBALAGEM] = 'Lata';

SELECT [NOME], [DATA DE NASCIMENTO] 
FROM [TABELA_CLIENTES]
WHERE [DATA DE NASCIMENTO] > '1995-12-31';

SELECT [NOME], [DATA DE NASCIMENTO] 
FROM [TABELA_CLIENTES]
WHERE YEAR([DATA DE NASCIMENTO]) > '1995';


/* CONDIÇÕES COMBINADAS */

SELECT [NOME], [BAIRRO] 
FROM [TABELA_CLIENTES]
WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO] = 'Tijuca';

SELECT [NOME], [ESTADO], [PRIMEIRA COMPRA] 
FROM [TABELA_CLIENTES]
WHERE [PRIMEIRA COMPRA] = '1' AND [ESTADO] = 'SP';


/* DESAFIO */

select * from TABELA_VENDEDORES
where [PERCENTUAL COMISSAO] <= 8;

select * from TABELA_PRODUTOS
where [PRECO DE LISTA] < 6 and EMBALAGEM = 'Lata';

select * from TABELA_CLIENTES
where CIDADE <> 'São Paulo' and CIDADE <> 'Rio de Janeiro';


/* Alterando informações */

update TABELA_PRODUTOS
set [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9
where EMBALAGEM = 'Lata';

select * from TABELA_PRODUTOS;

update TABELA_PRODUTOS
set EMBALAGEM = 'Lata', [PRECO DE LISTA] = 8.10
where [CODIGO DO PRODUTO] = '1088126';


/* DELETE */
delete from TABELA_PRODUTOS
where [CODIGO DO PRODUTO] = '1004327';