--função contadora

DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT;
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(200));
DECLARE @CONTADOR_NOTAS INT;

SET @LIMITE_MINIMO = 1;
SET @LIMITE_MAXIMO = 1000000;

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
    SELECT @CONTADOR_NOTAS = COUNT(*) FROM [dbo].[NOTAS FISCAIS] WHERE NUMERO = @LIMITE_MINIMO
    IF @CONTADOR_NOTAS > 0
        BEGIN
            INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS) VALUES (@LIMITE_MINIMO, 'É NOTA FISCAL')
        END
    ELSE
        BEGIN
            INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS) VALUES (@LIMITE_MINIMO, 'NÃO É NOTA FISCAL')
        END
    SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
END
SELECT * FROM @TABELA_NUMEROS ORDER BY NUMERO


--call
SELECT MIN(NUMERO), MAX(NUMERO) FROM [dbo].[NOTAS FISCAIS]



--funcao pega notas_fiscais

CREATE FUNCTION ListaNotasCliente (@CPF AS VARCHAR(11))
RETURNS TABLE
AS
RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT * FROM [dbo].[ListaNotasCliente]('1471156710')


--ALTERANDO UMA FUNÇÃO
CREATE FUNCTION Enderecocompleto
(@ENDERECO VARCHAR(100),
@BAIRRO VARCHAR(50),
@CIDADE VARCHAR(50),
@ESTADO VARCHAR(2),
@CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN

    DECLARE @ENDERECO_COMPLETO VARCHAR(250)
    SET @ENDERECO_COMPLETO = @ENDERECO + ' ' + 
    @BAIRRO + ' ' + @CIDADE + ' ' + @ESTADO + ', CEP ' + @CEP
    RETURN @ENDERECO_COMPLETO
END

--ALTER FUNCTION
ALTER FUNCTION Enderecocompleto
(@ENDERECO VARCHAR(100),
@BAIRRO VARCHAR(50),
@CIDADE VARCHAR(50),
@ESTADO VARCHAR(2),
@CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN

    DECLARE @ENDERECO_COMPLETO VARCHAR(250)
    SET @ENDERECO_COMPLETO = @ENDERECO + ' ' + 
    @BAIRRO + ' ' + @CIDADE + ' ' + @ESTADO + ', CEP ' + @CEP
    RETURN @ENDERECO_COMPLETO
END


--DELETANDO
CREATE FUNCTION ListaNotasCliente2 (@CPF AS VARCHAR(11))
RETURNS TABLE
AS
RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

--DROP FUNCTION
IF OBJECT_ID('ListaNotasCliente2', 'FN') IS NOT NULL
	DROP FUNCTION [dbo].[ListaNotasCliente2]